export enum ErrorCode {
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  NOT_YOUR_TURN = 'NOT_YOUR_TURN',
  ILLEGAL_MOVE = 'ILLEGAL_MOVE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  CONFLICT = 'CONFLICT',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
